---
github: LucasLarson
patreon: lucaslarson
open_collective: lucaslarson
ko_fi: lucaslarson
tidelift:  # 1 Tidelift platform-name/package-name like `npm/babel`
community_bridge:  # 1 Community Bridge project-name like `cloud-foundry`
liberapay: LucasLarson
issuehunt: lucaslarson
otechie:  # 1 Otechie username
custom:  # ≤ 4 custom sponsorship URLs like `['link1', 'link2']`
