---
# Configuration file for Mega-Linter
# https://nvuillam.github.io/mega-linter/configuration

# all, none, or list of linter keys
APPLY_FIXES: all

# Usually master or main
DEFAULT_BRANCH: main

# If you use `ENABLE`,
# all other languages/formats/tooling is disabled by default
# ENABLE:

# If you use `ENABLE_LINTERS`,
# all other linters are disabled by default
# ENABLE_LINTERS:

# DISABLE:
#   Uncomment to enable checks of abusive copy-pastes
#   - COPYPASTE
#   Uncomment to enable checks of spelling mistakes
#   - SPELL

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: true
