analyzer_rules:
  - explicit_self # enable in either analyzer_rules or opt_in_rules
  - unused_declaration # enable in either analyzer_rules or opt_in_rules
  - unused_import # enable in either analyzer_rules or opt_in_rules

excluded:
  - Carthage
  - Pods
  - UITests

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace_spacing
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - collection_element_alignment
  - colon
  - comma_spacing
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_initialization
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - enum_case_associated_values_counts
  - expiringtodo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
# - explicit_self # enable in either analyzer_rules or opt_in_rules
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_line_length
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_and_reduce
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - min_or_max_over_sorted_first_or_last
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_grouping_extension
  - no_space_in_method_call
  - notification_center_detachment
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace_spacing
  - operator_function_whitespace
  - operator_usage_whitespace
  - optional_enum_case_match
  - orphaned_doc_comment
  - overridden_methods_call_super
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_top-level_constant
  - private_action
  - private_actions
  - private_outlet
  - private_outlets
  - private_over_fileprivate
  - private_unit_test
  - prohibited_calls_to_super
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_@objc_attribute
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_set_access_control_rule
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - required_deinit
  - required_enum_case
  - returning_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_disable_command
  - switch_and_case_statement_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
# - unused_declaration # enable in either analyzer_rules or opt_in_rules
  - unused_enumerated
# - unused_import # enable in either analyzer_rules or opt_in_rules
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - variable_declaration_whitespace
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace # enable it when maxEmptyLines configuration exists
  - vertical_whitespace_after_opening_braces
  - vertical_whitespace_before_closing_braces
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctest_specific_matcher
  - xctfail_message
  - yoda_condition
  - yoda_condition_rule

file_length:
  warning: 5000
  error: 12000

indentation: 2

line_length:
  ignores_comments: false
  ignores_function_declarations: false
  ignores_interpolated_strings: false
  ignores_urls: false
  warning: 79

maxEmptyLines: 3

type_name:
  min_length: 4
  max_length:
    warning: 400
    error: 500
  excluded:
    - id
    - URL
    - GlobalAPIKey

vertical_whitespace:
  max_empty_lines: 3

disabled_rules:
