---
# .typo-ci.yml for Typo CI
# @MikeRogers0
# https://web.archive.org/web/20200610095834id_/typoci.com/documentation#header


dictionaries:
  - en
  - en_GB
  - fr


# Files and folders to ignore
excluded_files:
  - "esperanto/*"
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"


# Known spellings to ignore
excluded_words:
  - Affero  # GNU Affero Public License
  - Algis  # guillaumealgis/XcodeWarningsAsXcconfig
  - Biffle
  - calibreapp
  - Crashlytics
  - csharp  # CodeQL Analysis
  - cyberciti  # cyberciti.biz
  - dabutvin  # dabutvin/Imgbot
  - esolang
  - ffs
  - guillaumealgis  # guillaumealgis/XcodeWarningsAsXcconfig
  - ibiqlik  # ibiqlik/action-yamllint
  - Imgbot  # dabutvin/Imgbot
  - imgbotconfig  # dabutvin/Imgbot
  - jonreid  # jonreid/XcodeWarnings
  - jsonlint
  - ksh  # Korn shell
  - LucasLarson
  - lucaslarson
  - Mackup
  - markdownlint
  - minutiæ  # performatively pedantic minutiae
  - minuti\u00e6  # performatively pedantic minutiae
  - nixCraft  # Vivek Gite, cyberciti.biz
  - noninfringement  # GNU General Public License
  - peter-evans  # peter-evans/create-pull-request
  - rustup
  - sobolevn  # sobolevn/misspell-fixer-action
  - timey  # git --version < 2.23 is old-timey
  - typoci
  - uncommenting
  - VivekGite  # nixCraft, cyberciti.biz
  - yamllint

  # AsciiDoc
  - adoc
  - toclevels

  # CSS
  - webtv
  - konqueror
  - freebsd

  # Clang, GCC
  - argc
  - argv
  - cbp
  - climits
  - cplusplus
  - cstring
  - ctor
  - dtor
  - dylib
  - envc
  - envp
  - fcaret
  - fdiagnostics
  - fdiagnostics-fixit-info
  - fdiagnostics-parseable-fixits
  - fgnat
  - fgnu
  - fident
  - fixit  # fdiagnostics-fixit-info
  - fno
  - fshow
  - fstandalone
  - ftime
  - ftrapv
  - gch
  - gcno
  - gkd
  - ifndef
  - lai
  - latomic
  - llu
  - lstdc
  - parseable  # fdiagnostics-parseable-fixits
  - pch
  - pthread
  - slo
  - smod
  - strnlen
  - symvers  # github/gitignore@a080e36
  - unsequenced
  - Wcall
  - Wdefaulted
  - webfont
  - Weffc
  - Wextra
  - Wmemset
  - Wno
  - Woverriding
  - Wreturn
  - Wsizeof

  # DeepSource
  - gofmt
  - isort
  - standardjs
  - standardrb

  # Git
  - autocrlf
  - gitconfig
  - gmv  # homemade alias to `git mv`
  - gpgsign
  - lfs
  - lsi  # Jekyll’s latent semantic indexing
  - osxkeychain
  - precompose
  - textconv

  # GitHub
  - Ater  # TalAter/open-source-templates
  - gitsubmodule
  - gomod
  - Liberapay
  - ossar
  - Otechie
  - sarif  # OSSAR

  # Gitpod
  - bastet  # gitpod-io/gitpod
  - runtimes
  - tetris

  # Google
  - gtag

  # gunstage
  - gunstage  # `🔫  `git unstage` as a service https://git.io/gunstage
  - unstage
  - unstagers
  - unstaging
  - xab  # misanalysis of gunstage’s `printf '\xf0\x9f\x94\xab'`

  # JetBrains
  - iml
  - ipr
  - iws
  - mpeltonen
  - replstate
  - sbt-idea

  # Linux
  - nfs  # github/gitignore@4f7062e

  # macOS
  - donotpresent
  - icns
  - plutil

  # shell
  - euo

  # TextMate
  - tmbundle

  # Visual Studio
  # https://github.com/github/gitignore/blob/218a9/VisualStudio.gitignore
  - aps
  - ipch
  - ncb
  - ogs  # [Ll]ogs/
  - opensdf
  - scc
  - sdf
  - svclog
  - tli

  # Windows
  # https://github.com/toptal/gitignore/blob/78659/templates/Windows.gitignore
  - ekstop  # [Dd]esktop.ini
  - lnk
  - msix
  - msm
  - msp

  # Xcode
  - bcmp
  - bcopy
  - bzero
  - dealloc
  - ivars
  - mpi
  - optin
  - pbxproj
  - pbxuser
  - valist
  - vfork
  - xccheckout
  - xcconfig
  - xclang
  - xcrun
  - xcscmblueprint
  - xcsettings
  - xcshareddata
  - xcuserdata
  - xcworkspacedata

  # Zsh
  - Aquilina  # https://gitignore.io/api/zsh
  - ohmyzsh
  - omz  # ohmyzsh
  - robbyrussell  # https://gitignore.io/api/zsh
  - venv
  - zcalc
  - zcompdump
  - zdharma
  - zrecompile
  - zsdoc
  - zsh
  - zshelldoc
  - Zunit
  - zwc


# Filename spellchecking
spellcheck_filenames: false
