# .typo-ci.yml for Typo CI
# @MikeRogers0
# https://web.archive.org/web/20200610095834id_/typoci.com/documentation#header


dictionaries:
  - en
  - en_GB
  - fr

# Any files/folders we should ignore?
excluded_files:
  - "esperanto/*"
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"

# Any typos we should ignore?
excluded_words:
  - Biffle
  - Crashlytics
  - LucasLarson
  - Mackup
  - omz
  - rustup
  - typoci
  - uncommenting

  # Clang, GCC
  - cbp
  - climits
  - cstring
  - ctor
  - dtor
  - dylib
  - fcaret
  - fdiagnostics
  - fdiagnostics-fixit-info
  - fdiagnostics-parseable-fixits
  - fgnat
  - fgnu
  - fident
  - fno
  - fshow
  - fstandalone
  - ftime
  - ftrapv
  - gch
  - gcno
  - ifndef
  - lai
  - latomic
  - llu
  - lstdc
  - pch
  - pthread
  - slo
  - smod
  - strnlen
  - unsequenced
  - Wcall
  - Wdefaulted
  - Weffc
  - Wextra
  - Wmemset
  - Wno
  - Woverriding
  - Wreturn
  - Wsizeof

  # Git
  - gmv # homemade alias to `git mv`

  # GitHub funding
  - Liberapay
  - Otechie

  # JetBrains
  - iml
  - ipr
  - iws
  - mpeltonen
  - replstate
  - sbt-idea

  # macOS
  - donotpresent
  - icns

  # TextMate
  - tmbundle

  # Xcode
  - pbxproj
  - pbxuser
  - xccheckout
  - xcrun
  - xcscmblueprint
  - xcsettings
  - xcshareddata
  - xcuserdata
  - xcworkspacedata

  # Zsh
  - MichaelAquilina
  - robbyrussell
  - zdharma
  - zshelldoc
  - Zunit

# Would you like filenames to also be spellchecked?
spellcheck_filenames: false
