# .typo-ci.yml for Typo CI
# @MikeRogers0
# https://web.archive.org/web/20200610095834id_/typoci.com/documentation#header


dictionaries:
  - en
  - en_GB
  - fr

# Any files/folders we should ignore?
excluded_files:
  - "esperanto/*"
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"

# Any typos we should ignore?
excluded_words:
  - Biffle
  - LucasLarson
  - Mackup
  - typoci
  - uncommenting

  # Clang, GCC
  - fcaret
  - fdiagnostics
  - fno
  - fshow
  - fstandalone
  - ftime
  - lstdc
  - pthread
  - Wextra

  # Git
  - gmv # homemade alias to `git mv`

  # JetBrains
  - iml
  - ipr

  # TextMate
  - tmbundle

# Would you like filenames to also be spellchecked?
spellcheck_filenames: false
