alias gcm="git commit --message"
alias gfgs="git fetch && git status"
alias gu="git fetch && git submodule update --init --recursive && git status"
alias mu="cd ~/Dropbox/Mackup && mackup backup && git fetch && git submodule update --init --recursive && git status"
alias whihc="which"
