#!/usr/bin/env sh
abbr --global lf='eza --all --bytes --classify --color-scale --color=always --git --icons --long --no-permissions --no-user --octal-permissions --time-style=long-iso -- '\''{}'\'' '\''+'\'''
