#!/usr/bin/env sh
# abbreviations

## command
abbr --global cmand='command'
abbr --global cmmand='command'
abbr --global comadn='command'
abbr --global comand='command'
abbr --global comdn='command'
abbr --global comdna='command'
abbr --global commadn='command'
abbr --global commdn='command'
abbr --global commdna='command'
abbr --global commmand='command'
abbr --global commnd='command'
abbr --global comnd='command'

## exit
abbr --global eixt='exit'

## find
abbr --global lf='exa --all --bytes --classify --color-scale --color=always --git --icons --long --no-permissions --no-user --octal-permissions --time-style=long-iso -- {} +'

## help
abbr --global ehlp='help'
abbr --global --ehlp='--help'
abbr --global hellp='help'
abbr --global --hellp='--help'
abbr --global herl='help'
abbr --global --herl='--help'
abbr --global hlep='help'
abbr --global --hlep='--help'
abbr --global hlp='help'
abbr --global --hlp='--help'

## open
abbr --global oepn='open'
abbr --global opne='open'

## xtrace
abbr --global gitset='GIT_TRACE=2 GIT_TRACE_PACK_ACCESS=2 GIT_TRACE_PACKET=2 GIT_TRACE_PERFORMANCE=2 GIT_TRACE_SETUP=2 GIT_MERGE_VERBOSITY=5 GIT_CURL_VERBOSE=1 GIT_TRACE2_EVENT_NESTING="$(command getconf -- UINT_MAX)" GIT_PROGRESS_DELAY=0 GIT_TRACE2_EVENT=1 GIT_TRACE_REFS=1'

## zshrc
abbr --global zhsrc='zshrc'
abbr --global zsrhc='zshrc'
abbr --global zzshrc='zshrc'
