---
name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.7
        with:
          use-verbose-mode: 'yes'
          base-branch: 'main'

name: Broken link check
on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/link-checker@v1.0.1
      with:
        # Required:
        # url: 'https://...'
        # optional:
        honorRobotExclusions: false
        ignorePatterns: 'archive.org,archive.today,github,google'
        recursiveLinks: false # Check all urls on all reachable pages (could take a while)
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
