---
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Validate links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate links
        uses: ad-m/report-link-action@sha256:57d657e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
