---
name: Check Markdown links

on:
  push:
    branches:
      - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.8
        with:
          use-verbose-mode: 'yes'
          base-branch: 'main'
