---
name: Validate links

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: ad-m/report-link-action@sha256:57d657e6b5f59cd95e3ce38a08241f2a81bbe533
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
