---
# https://github.com/dylanaraps/pure-sh-bible/commit/9d54e96011
name: Shellcheck
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        run: ./.github/shellcheck_markdown.sh
